export default colors = {
  white: '#FFFFFF',
  purpleLight: '#C2B6FC',
  purpleMedium: '#5A4DCC',
  purpleDark: '#1E1A61',
  otherPurple: '#ADAAF1',
  blue: '#68A1CF',
  gray: '#83898C',
  lightGray: '#EEECF1',
  orange: '#D06053',
  pinkDark: '#5B304C',
  pinkLight: '#DD6C7E',
  isCheckedColor: '#5A4DCC',
  isUncheckedColor: '#5A4DCC',
  datePickTestColor: '#5A4DCC',
  purpleSuperDark: '#1b057c',
  purpleSuperLight: '#938fe8',
};
