const constans = {
  welcome: 'Welcome',
  staySafe: 'Stay safe!',
  covidGlobal: 'COVID is global!',
  subtitleOne: 'Help us to prevent the spread.',
  subtitleTwo: 'Protect yourself and others.',
  subtitleThree:
    'We are all in this together and we will get through this, together.',
  tasksTitle: 'Your tasks',
  email: 'Email',
  pw: 'Password',
  login: 'Log in',
  forgotPW: 'Forgot password?',
  mainQuest: 'What do you want to do?',
  urlAPI: 'https://hidden-cliffs-21927.herokuapp.com/user/sign_in',
  QuestionSymptoms: 'What symptoms do you have?',
  testType: 'Test Type',
  viralTest: 'Viral test',
  bodyTest: 'Body test',
  done: 'Done',
  testDetails: 'Test details',
  testResult: 'Test result',
  selectType: 'Select test type:',
  testDate: 'Select your test result date',
  selectResult: 'Select test result:',
  testResultDate: 'Select your test Date',
  qrTitle: 'QR Place Scan',
  typeUser: 'usuario',
  typePass: 'contrasenia',
};
export default constans;
