const constans = {
  asyncTokenVar: 'userToken',
  welcome: 'Welcome',
  greeting: 'Hello!',
  staySafe: 'Stay safe!',
  covidGlobal: 'COVID is global!',
  subtitleOne: 'Help us to prevent the spread.',
  subtitleTwo: 'Protect yourself and others.',
  subtitleThree:
    'We are all in this together and we will get through this, together.',
  tasksTitle: 'Your Tasks',
  locations: 'Locations',
  locationsDescription: 'All locations you have been',
  registerLab: 'Register labs',
  registerLabDescription: 'All tests you have made',
  prevention: 'COVID-19',
  preventionDescription: 'Coronavirus instructions and preventions',
  email: 'Email',
  pw: 'Password',
  loginGreeting: 'Please, login and stay safe!',
  login: 'Login',
  forgotPW: 'Forgot password?',
  errorLoginFail: 'Login failed!',
  urlService: 'https://hidden-cliffs-21927.herokuapp.com/api/',
  QuestionSymptoms: 'What symptoms do you have?',
  testType: 'Test Type',
  viralTest: 'Viral test',
  bodyTest: 'Body test',
  done: 'Done',
  signOutResDataCode: 'SSN_CLOSE',
  errorSignOut: 'Error al cerrar sesión...',
  testDetails: 'Test details',
  testResult: 'Test result',
  selectType: 'Select test type',
  selectDate: 'Select date',
  testDate: 'Select your test result date',
  selectResult: 'Select test result:',
  testResultDate: 'Select your test Date',
  qrTitle: 'QR Place Scan',
  typeUser: 'usuario',
  typePass: 'contrasenia',
  wearMask: 'Wear a mask',
  wearMaskSub:
    'Wear a mask that covers your nose and mouth to help protect yourself and others.',
  washHands: 'Wash your hands',
  washHandsSub: 'Wash your hands often with soap and water.',
  keepDistance: 'Keep your distance',
  keepDistanceSub: 'Stay 6 feet apart from others who don’t live with you.',
  handSanitizer: 'Use hand sanitizer',
  handSanitizerSub: ' Use hand sanitizer if soap and water aren’t available.',
  stayHome: 'Stay home',
  stayHomeSub: 'Get a COVID-19 vaccine when it is available to you.',
  titleLocation: 'Locations',
  listTest: 'Your list test',
  addNewTest: 'Add new test',
  incidentResportTitle: 'Incident Reports',
  incidentResportDescription: 'See currently incidents',
  ReportTitle: 'Incident Report',
  urlReport:
    'https://hidden-cliffs-21927.herokuapp.com/api/reports/place_reports',
};
export default constans;
